---
abstract: 'Catalyst based application'
author:
  - root
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MyApp
no_index:
  directory:
    - inc
    - t
requires:
  Authen::Passphrase::BlowfishCrypt: 0
  Catalyst::Action::RenderView: 0
  Catalyst::ActionRole::ACL: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::Memcached: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.90002
  Catalyst::View::Email: 0
  CatalystX::SimpleLogin: 0
  Config::General: 0
  Crypt::PassGen: 0
  DBIx::Class::PassphraseColumn: 0
  HTML::FormHandler: 0
  HTML::FormHandler::Model::DBIC: 0
  Method::Signatures::Simple: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
